# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract branch name and commit hash
      id: vars
      run: |
        echo "BRANCH_NAME=dev" >> $GITHUB_ENV
        echo "COMMIT_HASH=${GITHUB_SHA::8}" >> $GITHUB_ENV
    
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          github:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
        labels: |
          org.opencontainers.image.title=github
          org.opencontainers.image.version=${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
          org.opencontainers.image.description="A Docker image for GitHub project from branch ${{ env.BRANCH_NAME }} with commit ${{ env.COMMIT_HASH }}"  
